sudo: false
language: generic
matrix:
  include:
    - name: "archlinux"
      os: linux
      env: CONTAINER=archlinux
      services: docker
    - name: "Ubuntu 18.04"
      os: linux
      env: CONTAINER=ubuntu1804
      services: docker
install:
  - pushd $TRAVIS_BUILD_DIR
  - docker-compose build $CONTAINER-test
script:
  - docker-compose run $CONTAINER-test
