#!/bin/bash


function directory_for_folder_list() {
  local error_log=/dev/null
  if [ $# == 1 ]
  then
    echo $1
  elif [ -d "${1}/${2}" ]
  then
    echo $(directory_for_folder_list "${1}/${2}" "${@:3}")
  else
    for directory in $(find "${1}" -name "${2}" -type d 2>${error_log})
    do
      directory_for_folder_list "${directory}" "${@:3}"
      break
    done
  fi
}

function say() {
  echo "doc: ${1}."
}

function insert_environment_variable() {
  if grep -q "^export DOC_STORAGE_DIRECTORY=" "${HOME}/.bashrc" 2>&1 > /dev/null
  then
    sed --follow-symlinks -i -e "s|^export DOC_STORAGE_DIRECTORY=.*$|export DOC_STORAGE_DIRECTORY=\"${1}\"|g" "${HOME}/.bashrc" 2>&1 > /dev/null
  else
    echo "export DOC_STORAGE_DIRECTORY=\"${1}\"" >> "${HOME}/.bashrc" 2> /dev/null
  fi
}

function init() {
  directory="$(directory_for_folder_list "$(pwd)" "${@}")"

  if [ ! -d "${directory}" ]
  then
    say "'${1}' is not a directory"
    exit 1
  elif [ "$(git --version 2>&1 > /dev/null)" ]
  then
    say "git is not installed"
    exit 3
  fi

  pushd "${directory}" 2>&1 > /dev/null
  if [ ! "$(git status 2>&1 > /dev/null)" ]
  then
    # git directory
    if [[ $(git status --porcelain) ]]
    then
      # unstaged changes
      git add . 2>&1 > /dev/null
      git commit -m "Install doc thus all files are committed." 2>&1 > /dev/null
    fi
    popd 2>&1 > /dev/null

    insert_environment_variable "${directory}"
    say "Successfully used repo at '${directory}'"
    exit 0
  fi
  popd 2>&1 > /dev/null

  if [ "$(ls -A "${directory}")" ]
  then
    say "Directory not empty '${directory}'"
    exit 2
  fi

  pushd "${directory}" 2>&1 > /dev/null
  git init 2>&1 > /dev/null
  popd 2>&1 > /dev/null

  insert_environment_variable "${directory}"
  say "Successfully initialised repo at '${directory}'"
}

function directory_add() {
  if [ "$DOC_STORAGE_DIRECTORY" == "" ]
  then
    say "'DOC_STORAGE_DIRECTORY' unset. Use 'doc init FOLDER' first"
    exit 5
  fi

  directory="$(directory_for_folder_list "$DOC_STORAGE_DIRECTORY" "${@:1:${#}-1}")"
  new_directory="${@: -1}"
  new_path="$directory/$new_directory"
  if [ -d "$new_path" ]
  then
    say "'$new_directory' already exists"
    exit 7
  fi

  mkdir "$new_path"
  say "Successfully created directory '${new_path#${DOC_STORAGE_DIRECTORY}/}'"
  exit 0
}

function directory() {
  if [ "$1" == "add" ]
  then
    if [ "$#" == 1 ]
    then
      say "Please give a directory name"
      exit 6
    fi
    shift
    directory_add $@
  fi

  say "Please give a valid command"
  exit 8
}

if [ "$1" == "init" ]
then
  if [ "$#" == 1 ]
  then
    say "Please give a directory"
    exit 4
  fi
  shift
  init $@
elif [ "$1" == "directory" ]
then
  shift
  directory $@
fi
