#!/bin/bash

function say() {
  echo "doc: ${1}."
}

function error_exit() {
  say "$1" 1>&2
  exit $2
}

function sub_error() {
  error_exit "Error in sub routine" 11
}

function directory_for_folder_list() {
  local error_log=/dev/null
  if [ $# == 1 ]
  then
    echo $1
  elif [ -d "${1}/${2}" ]
  then
    echo $(directory_for_folder_list "${1}/${2}" "${@:3}")
  else
    for directory in $(find "${1}" -name "${2}" -type d 2>${error_log})
    do
      directory_for_folder_list "${directory}" "${@:3}"
      break
    done
  fi
}

function insert_environment_variable() {
  if grep -q "^export DOC_STORAGE_DIRECTORY=" "${HOME}/.bashrc" 2>&1 > /dev/null
  then
    sed --follow-symlinks -i -e "s|^export DOC_STORAGE_DIRECTORY=.*$|export DOC_STORAGE_DIRECTORY=\"${1}\"|g" "${HOME}/.bashrc" 2>&1 > /dev/null
  else
    echo "export DOC_STORAGE_DIRECTORY=\"${1}\"" >> "${HOME}/.bashrc" 2> /dev/null
  fi
}

function init() {
  directory="$(directory_for_folder_list "$(pwd)" "${@}")"

  if [ ! -d "${directory}" ]
  then
    error_exit "'${1}' is not a directory" 1
  elif [ "$(git --version 2>&1 > /dev/null)" ]
  then
    error_exit "git is not installed" 3
  fi

  pushd "${directory}" 2>&1 > /dev/null
  if [ ! "$(git status 2>&1 > /dev/null)" ]
  then
    # git directory
    if [[ $(git status --porcelain) ]]
    then
      # unstaged changes
      git add . 2>&1 > /dev/null
      git commit -m "Install doc thus all files are committed." 2>&1 > /dev/null
    fi
    popd 2>&1 > /dev/null

    insert_environment_variable "${directory}"
    say "Successfully used repo at '${directory}'"
    return 0
  fi
  popd 2>&1 > /dev/null

  if [ "$(ls -A "${directory}")" ]
  then
    error_exit "Directory not empty '${directory}'" 2
  fi

  pushd "${directory}" 2>&1 > /dev/null
  git init 2>&1 > /dev/null
  popd 2>&1 > /dev/null

  insert_environment_variable "${directory}"
  say "Successfully initialised repo at '${directory}'"
}

function check_storage_envvar() {
  if [ "$DOC_STORAGE_DIRECTORY" == "" ]
  then
    error_exit "'DOC_STORAGE_DIRECTORY' unset. Use 'doc init FOLDER' first" 5
  fi
}

function directory_add() {
  check_storage_envvar

  directory="$(directory_for_folder_list "$DOC_STORAGE_DIRECTORY" "${@:1:${#}-1}")"
  new_directory="${@: -1}"
  new_path="$directory/$new_directory"
  if [ -d "$new_path" ]
  then
    error_exit "'$new_directory' already exists" 7
  fi

  mkdir "$new_path"
  say "Successfully created directory '${new_path#${DOC_STORAGE_DIRECTORY}/}'"
  return 0
}

function directory() {
  if [ "$1" == "add" ]
  then
    if [ "$#" == 1 ]
    then
      error_exit "Please give a directory name" 6
    fi
    shift
    directory_add $@
    return $?
  fi

  say "Please give a valid command"
  exit 8
}

function add_list() {
  check_storage_envvar

  directory="$(directory_for_folder_list "$DOC_STORAGE_DIRECTORY" "${@:1:${#}-1}")"
  file="${@: -1}"
  new_file="$(basename $file)"
  new_path="$directory/${new_file}.gpg"
  if [ -f "$file" ]
  then
    gpg -r croesch -o "$new_path" -e "$file"
    rm "$file"
    say "Successfully added '$file'"
    return 0
  fi

  error_exit "'$file' not found" 10
}

function add() {
  if [ "$#" == 0 ]
  then
    error_exit "Please give a file to add" 9
  fi

  add_list $@
}

if [ "$1" == "add" ]
then
  shift
  add $@
elif [ "$1" == "init" ]
then
  if [ "$#" == 1 ]
  then
    say "Please give a directory"
    exit 4
  fi
  shift
  init $@
elif [ "$1" == "directory" ]
then
  shift
  directory $@
fi
